### ISSUE TITLE
Problem to recreate the result

### ISSUE THREAD

**Issue by agrans** [Fabian-Sc85/non-invasive-bp-estimation-using-deep-learning#2]
Hi, I have some problems recreating the result from the article when following the instruction.

- "download_minic_iii_records.py"  crashes when it tries to download the files in "MIMIC-III_ppg_dataset_records.txt" with the error: 
Traceback (most recent call last):
  File "download_mimic_iii_records.py", line 111, in <module>
    download_mimic_iii_records(RecordsFile, OutputPath)
  File "download_mimic_iii_records.py", line 73, in download_mimic_iii_records
    abp_FidPoints = hp.process(abp, fs)
  File "/home/agrans/Documents/non-invasive-bp-estimation-using-deep-learning/venv/lib/python3.8/site-packages/heartpy/heartpy.py", line 289, in process
    working_data = fit_peaks(hrdata, rol_mean, sample_rate, bpmmin=bpmmin,
  File "/home/agrans/Documents/non-invasive-bp-estimation-using-deep-learning/venv/lib/python3.8/site-packages/heartpy/peakdetection.py", line 305, in fit_peaks
    raise BadSignalWarning('\n----------------\nCould not determine best fit for \
heartpy.exceptions.BadSignalWarning: 

- "download_minic_iii_records.py" seams to not create ".mat"-types which seams to be required for "prepare_MIMIC_dataset.py" and all data is skipped. 

What am I doing wrong when following the instructions in the README?

**Comment by Fabian-Sc85** [comment]
Hi, could you give me the name of the particular record at which the script fails so that I can reproduce this error? Thanks.

**Comment by agrans** [comment]
The first four it crashes on are:
39/3982843
38/3889764_0025
38/3879205_0027
31/3168979

**Comment by Fabian-Sc85** [comment]
It seems the problem arises if the heartpy package is unable to extract systolic and diastolic peaks from the ABP/PPG signals. I have "solved" the problem by skipping such records. However, I am going to publish the MIMIC-B dataset used in the paper as soon as possible
